#!/usr/bin/env bash
# else statement
if [ -e school ]
then
echo "School file exists"
if [ -s school ]
then
echo "School file is not empty"
else 
echo "school file is empty"
fi
if [ -f school ]
then
echo "School is a regular file"
fi
else 
echo "school file doesn't exist"
fi
